backend/urls.py
from django.urls import path
from backend.views import (
    HomePageView,
    ProductDetailView,
    CrateCartView,
    RemoveCartView,
    OrderSummaryView,
    RemoveSingleCartItemView,
    CheckoutView,
    PaymentView,
    RefundView,
)

app_name = 'backend'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path("product/<int:pk>/", ProductDetailView.as_view(), name='product'),
    path("add-to-cart/<int:product_id>/", CrateCartView.as_view(), name='add_to_cart'),
    path("remove-from-cart/<int:product_id>", RemoveCartView.as_view(), name='remove-from-cart'),
    path("orders/", OrderSummaryView.as_view(), name='orders'),
    path("remove-single-cart-item/<int:product_id>", RemoveSingleCartItemView.as_view(), name='remove-single-cart-item'),
    path("checkout/", CheckoutView.as_view(), name='checkout'),
    path("payment/<payment_method>/", PaymentView.as_view(), name='payment'),
    path("request-refund/", RefundView.as_view(), name='request-refund'),
]

django_ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('backend.urls', namespace='backend')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/models.py
from django.db import models
from django.contrib.auth.models import User

CATEGORY_CHOICES = [
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear'),
]

ADDRESS_CHOICES = [
    ('B', 'Billing'),
    ('S', 'Shipping'),
]


STATE_CHOICES = [
    ('Chittagong', (
            ('cbra', 'Brahmanbaria'),
            ('ccom', 'Comilla'),
            ('clak', 'Lokshmipur'),
            ('cnoa', 'Noakhali'),
            ('cfen', 'Feni'),
            ('ckha', 'Khagrachhari'),
            ('cran', 'Rangamati'),
            ('cban', 'Bandarban'),
            ('cchi', 'Chittagong'),
            ('ccox', "Cox's Bazar"),
        )
     ),
    ('Barisal', (
        ('bbra', 'Barisal'),
        ('bbar', 'Barguna'),
        ('bhol', 'Bhola'),
        ('bjal', 'Jhalokati'),
        ('bpat', 'Patuakhali'),
        ('bpir', 'Pirojpur'),
        )
     ),
    ('Dhaka', (
        ('ddha', 'Dhaka'),
        ('dgha', 'Ghazipur'),
        ('dkis', 'Kishoreganj'),
        ('dman', 'Manikganj'),
        ('dmun', 'Munshiganj'),
        ('dnar', 'Narayanganj'),
        ('dnrs', 'Narasingdi'),
        ('dtan', 'Tangail'),
        ('dfar', 'Faridpur'),
        ('dgop', 'Gopalganj'),
        ('dmad', 'Madaripur'),
        ('draj', 'Rajbari'),
        ('dsha', 'Shariatpur'),
        )
     ),
]

COUNTRY_CHOICES = [
    ('BD', 'Bangladesh'),
]


class Product(models.Model):
    title = models.CharField(max_length=200, blank=False)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name="available from")
    description = models.TextField(verbose_name="more info")
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=3)
    views = models.PositiveIntegerField(default=0)
    image = models.ImageField()

    def __str__(self):
        return self.title


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=1, blank=False)
    is_ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity}  -  {self.product.title}"

    def get_total_price(self):
        return self.quantity * self.product.price

    def get_total_discount_price(self):
        return self.quantity * self.product.discount_price

    def get_saving_price(self):
        return self.get_total_price() - self.get_total_discount_price()

    def get_final_cart_price(self):
        if self.product.discount_price:
            return self.get_total_discount_price()
        else:
            return self.get_total_price()


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart_products = models.ManyToManyField(Cart, related_name='cart')
    is_ordered = models.BooleanField(default=False)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey('Address', on_delete=models.SET_NULL, blank=True, null=True, related_name='billing_address')
    shipping_address = models.ForeignKey('Address', on_delete=models.SET_NULL, blank=True, null=True, related_name='shipping_address')
    is_delivered = models.BooleanField(default=False)
    is_received = models.BooleanField(default=False)
    ref_code = models.CharField(max_length=20)
    is_refund_requested = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def final_order_price(self):
        total = 0
        for cart in self.cart_products.all():
            total += cart.get_final_cart_price()
        return total


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100, blank=True)
    country = models.CharField(choices=COUNTRY_CHOICES, max_length=2)
    state = models.CharField(choices=STATE_CHOICES, max_length=4)
    zip_code = models.CharField(max_length=15, blank=True)
    address_type = models.CharField(choices=ADDRESS_CHOICES, max_length=1)
    default = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Addresses'

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    is_accepted = models.BooleanField(default=False)

    def __str__(self):
        return self.order.ref_code

templates/pages/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <!--Main layout-->
    <main>
        <div class="container wow fadeIn">
            <div class="row">
                <div class="col-md-8">
                    <div class="card my-4 border-0">
{#                        <h2 class="card-header h2 deep-purple white-text text-center">Checkout</h2>#}
                        <form method="post" class="card-body" action="{% url 'backend:checkout' %}">
                            {% csrf_token %}
                            <!-- Shipping form -->
                            <h3 class="card-title text-center text-muted white-text font-weight-light special-color py-2 rounded-pill z-depth-2"><i class="fas fa-map-marked-alt fa-sm"></i> Shipping Address</h3>
                            <div id="shipping-form">
                                <div class="md-form my-5">
                                    {{ form.shipping_address }}
                                    <label for="{{ form.shipping_address.id_for_label }}" class="">Street address</label>
                                </div>
                                <div class="md-form mb-4">
                                    {{ form.shipping_address2 }}
                                    <label for="{{ form.shipping_address2.id_for_label }}" class="">Apartment address (optional)</label>
                                </div>

                                <!--Grid row-->
                                <div class="row">
                                    <!--Grid column-->
                                    <div class="col-lg-4 col-md-12 mb-4">
                                        <label for="{{ form.shipping_country.id_for_label }}">Country</label>
                                        {{ form.shipping_country }}
                                        <div class="invalid-feedback">
                                            Please select a valid country.
                                        </div>
                                    </div>
                                    <!--Grid column-->

                                    <!--Grid column-->
                                    <div class="col-lg-4 col-md-6 mb-4">
                                        <label for="{{form.shipping_state.id_for_label}}">State</label>
                                        {{ form.shipping_state }}
                                        <div class="invalid-feedback">
                                            Please provide a valid state.
                                        </div>
                                    </div>
                                    <!--Grid column-->

                                    <!--Grid column-->
                                    <div class="col-lg-4 col-md-6 mb-4">
                                        <label for="{{ form.shipping_zip_code.id_for_label }}">Zip Code</label>
                                        {{ form.shipping_zip_code }}
                                        <div class="invalid-feedback">
                                            Zip code required.
                                        </div>
                                    </div>
                                    <!--Grid column-->
                                </div>
                                <!--Grid row-->
                                <div class="custom-control custom-checkbox">
                                    {{ form.same_billing_address }}
                                    <label class="custom-control-label" for="{{form.same_billing_address.id_for_label}}">Billing address is same as my Shipping address</label>
                                </div>
                                <div class="custom-control custom-checkbox">
                                    {{ form.set_default_shipping_address }}
                                    <label class="custom-control-label" for="{{form.set_default_shipping_address.id_for_label}}">Set this information as default Shipping address</label>
                                </div>
                            </div>
                            <div class="custom-control custom-checkbox">
                                {{ form.use_default_shipping_address }}
                                <label class="custom-control-label" for="{{form.use_default_shipping_address.id_for_label}}">Use default address: <span class="text-primary grey lighten-4">{{ default_shipping_address.street_address|truncatechars:35 }}</span></label>
                            </div>
                            <!-- Shipping form -->

                            <!-- Billing form -->
                            <h3 class="card-title text-center text-muted white-text font-weight-light special-color mt-5 py-2 rounded-pill z-depth-2"><i class="fas fa-money-check-alt fa-sm"></i> Billing Address</h3>
                            <div id="billing-form">
                                <div class="md-form my-5">
                                    {{ form.billing_address }}
                                    <label for="{{ form.billing_address.id_for_label }}" class="">Street address</label>
                                </div>
                                <div class="md-form mb-5">
                                    {{ form.billing_address2 }}
                                    <label for="{{ form.billing_address2.id_for_label }}" class="">Apartment address (optional)</label>
                                </div>

                                <!--Grid row-->
                                <div class="row">
                                    <!--Grid column-->
                                    <div class="col-lg-4 col-md-12 mb-4">
                                        <label for="{{ form.billing_country.id_for_label }}">Country</label>
                                        {{ form.billing_country }}
                                        <div class="invalid-feedback">
                                            Please select a valid country.
                                        </div>
                                    </div>
                                    <!--Grid column-->

                                    <!--Grid column-->
                                    <div class="col-lg-4 col-md-6 mb-4">
                                        <label for="{{form.billing_state.id_for_label}}">State</label>
                                        {{ form.billing_state }}
                                        <div class="invalid-feedback">
                                            Please provide a valid state.
                                        </div>
                                    </div>
                                    <!--Grid column-->

                                    <!--Grid column-->
                                    <div class="col-lg-4 col-md-6 mb-4">
                                        <label for="{{ form.billing_zip_code.id_for_label }}">Zip Code</label>
                                        {{ form.billing_zip_code }}
                                        <div class="invalid-feedback">
                                            Zip code required.
                                        </div>
                                    </div>
                                    <!--Grid column-->
                                </div>
                                <!--Grid row-->
                                <div class="custom-control custom-checkbox">
                                    {{ form.set_default_billing_address }}
                                    <label class="custom-control-label" for="{{form.set_default_billing_address.id_for_label}}">Set this as my default billing address</label>
                                </div>
                            </div>
                            <div class="custom-control custom-checkbox">
                                {{ form.use_default_billing_address }}
                                <label class="custom-control-label" for="{{form.use_default_billing_address.id_for_label}}">Use my default billing address: <span class="text-primary grey lighten-3">{{ default_billing_address.street_address|truncatechars:35 }}</span></label>
                            </div>

                        <!-- Billing form -->
                            <h3 class="text-center text-muted white-text font-weight-light special-color mt-5 py-2 rounded-pill z-depth-3">Payment Options</h3>
                            <div class="d-block my-5 text-center">
                                {% for method in form.payment_method %}
                                    <div class="custom-control custom-radio custom-control-inline">
                                        {{ method.tag }}
                                        <label class="custom-control-label" for="{{ method.id_for_label }}">{{ method.choice_label }}</label>
                                    </div>
                                {% endfor %}
                            </div>
                            <hr>
                            <div class="text-center">
                                <button class="btn btn-unique btn-lg" type="submit">Proceed <i class="fa fa-angle-double-right fa-lg ml-3" aria-hidden="true"></i></button>
                            </div>
                        </form>
                    </div>
                </div>
                <!--/.Card-->

                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-4 my-4">
                    {% include 'components/_cart_preview.html' %}
                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->
        </div>
    </main>
    <!--Main layout-->
    {% include 'components/_bottom_bar.html' %}

{% endblock content %}

{% block extra_scripts %}
    <script>
    let shipping_form = $('#shipping-form');
    let billing_form = $('#billing-form');

    let same_billing_address = document.querySelector("input[name=same_billing_address]");
    let default_shipping = document.querySelector("input[name=use_default_shipping_address]");
    let default_billing = document.querySelector("input[name=use_default_billing_address]");

    default_shipping.addEventListener('change', function () {
        if (this.checked) {
            shipping_form.hide()
        } else {
            shipping_form.show()
        }
    });

    same_billing_address.addEventListener('change', function () {
        if(this.checked){
            billing_form.hide();
        } else {
            billing_form.show();
        }
    });

    default_billing.addEventListener('change', function () {
        if (this.checked) {
            billing_form.hide()
        } else {
            billing_form.show()
        }
    });

    </script>
{% endblock extra_scripts %}

templates/pages/index.html
{% extends 'base.html' %}
{% block content %}
    <!--Main layout-->
    <!--Navbar-->
    {% include 'components/_inner_nav.html' %}
    <!--/.Navbar-->
    <main>
        <div class="container">
            <!--Section: Products v.3-->
            <section class="text-center mb-3">
                <div class="row wow fadeIn">
                <!--Grid row-->
                {% for product in object_list %}
                        <div class="col-lg-3 col-md-4 col-6 mb-4">
                            <!--Card-->
                            <div class="card">
                                <!--Card image-->
                                <div class="view overlay">
                                    <img src="{{ product.image.url }}" class="card-img-top"
                                         alt="">
                                    <a href="{% url 'backend:product' product.pk %}">
                                        <div class="mask rgba-white-slight"></div>
                                    </a>
                                </div>
                                <!--Card image-->
                                <!--Card content-->
                                <div class="card-body text-center">
                                    <!--Category & Title-->
                                    <a class="grey-text">
                                        <h5>{{ product.get_category_display }}</h5>
                                    </a>
                                    <h5>
                                        <strong>
                                            <a class="dark-grey-text">{{product.title}}</a>
                                        </strong>
                                    </h5>
                                    {% if product.discount_price %}
                                        <del class="grey-text">${{ product.price }}</del> <h4 class="font-weight-bold pink-text d-inline"> ${{ product.discount_price }}</h4>
                                    {% else %}
                                        <h4 class="font-weight-bold text-dark d-inline"><strong>${{ product.price }}</strong></h4>
                                    {% endif %}
                                </div>
                                <!--Card content-->
                            </div>
                            <!--Card-->
                        </div>
                        <!--Fourth column-->
                {% empty %}
                    Nothing Found
                {% endfor %}
                <!--Grid row-->
                </div>
            </section>
            <!--Section: Products v.3-->

            <!--Pagination-->
        {% if is_paginated %}
            <nav class="d-flex justify-content-center wow fadeIn">
                <ul class="pagination pg-blue">
                    {% if page_obj.has_previous %}
                        <!--Arrow left-->
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true"><i class="fas fa-angle-double-left" aria-hidden="true"></i></span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" aria-label="Previous">
                                <span aria-hidden="true"><i class="fas fa-angle-double-left" aria-hidden="true"></i></span>
                            </a>
                        </li>
                    {% endif %}
                    {% for page in paginator.page_range %}
                        {% if page_obj.number == page %}
                            <li class="page-item active">
                                <a class="page-link" href="?page={{ page }}">{{ page }}
                                    <span class="sr-only">Current</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page }}">{{ page }}
                                </a>
                            </li>
                        {% endif %}
                    {% endfor %}


                <!-- Next -->
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true"><i class="fas fa-angle-double-right" aria-hidden="true"></i></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" aria-label="Next">
                                <span aria-hidden="true"><i class="fas fa-angle-double-right" aria-hidden="true"></i></span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% else %}

        {% endif %}
            <!--Pagination-->
        </div>
    </main>
  <!--Main layout-->
{% endblock content %}

{% block extra_body %}
    {% include 'components/_bottom_bar.html' %}
{% endblock extra_body %}

templates/pages/orders.html
{% extends 'base.html' %}
{% block content %}
    <!--Main layout-->
    <main>
        <div class="container">
            <!--Section: Products v.3-->
            <section class="text-center mb-3">
                <div class="row wow fadeIn">
                    <div class="table-responsive mt-4">
                        <h2>Order Summery</h2>
                        <table class="table table-striped">
                            <thead class="blue-gradient white-text">
                            <tr class="font-weight-bold">
                                <th scope="col">#</th>
                                <th scope="col"><i class="fas fa-th-list"></i></th>
                                <th scope="col"><i class="fas fa-dollar-sign mr-2" aria-hidden="true"></i></th>
                                <th scope="col"><i class="fas fa-shopping-cart mr-1"></i></th>
                                <th scope="col"><i class="fas fa-cash-register mr-2" aria-hidden="true"></i></th>
                                <th scope="col"><i class="fas fa-hand-holding-usd" aria-hidden="true"></i></th>
                                <th scope="col"><i class="fas fa-trash-alt" aria-hidden="true"></i></th>
                            </tr>
                            </thead>

                            {% if order %}
                                <tbody>
                                {% for item in order.cart_products.all %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td><a href="{% url 'backend:product' item.product.id %}">{{ item.product.title }}</a></td>
                                        <td >
                                            {% if item.product.discount_price %}
                                                <del class="text-muted">{{ item.product.price }}</del>
                                                <span class="font-weight-bold">{{ item.product.discount_price }}</span>
                                            {% else %}
                                                {{ item.product.price }}
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a class="mr-lg-2" href="{% url 'backend:remove-single-cart-item' item.product.id %}"><i class="fas fa-minus fa-sm"></i></a>
                                            {{ item.quantity }}
                                            <a class="ml-lg-2" href="{% url 'backend:add_to_cart' item.product.id %}"><i class="fas fa-plus fa-sm"></i></a>
                                        </td>
                                        <td>
                                            {% if item.product.discount_price %}
                                                {{ item.get_total_discount_price }}
                                            {% else %}
                                                {{ item.get_total_price }}
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if item.product.discount_price %}
                                                <span class="green-text darken-3"><strong>{{ item.get_saving_price }}</strong></span>
                                            {% else %}
                                                <span>00.0</span>
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a class="red-text" href="{% url 'backend:remove-from-cart' item.product.id %}"><i class="fas fa-trash-alt" aria-hidden="true"></i></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                <tr>
                                    <td class="font-weight-bold" colspan="4">Pay Amount: </td>
                                    <td class="font-weight-bold" colspan="3">${{ order.final_order_price }}</td>
                                </tr>
                                </tbody>
                                <tr>
                                    <td colspan="7">
                                        <a href="{% url 'backend:checkout' %}" class="btn btn-pink" >Checkout</a>
                                        <a href="{% url 'backend:home' %}" class="btn btn-primary">Continue Shopping</a>
                                    </td>
                                </tr>
                            {% else %}
                                <h2 class="red-text">Your cart is empty!</h2>
                            {% endif %}
                        </table>

                    </div>
                </div>
            </section>
        </div>
    </main>
  <!--Main layout-->
{% endblock content %}

templates/pages/refund-request.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="card my-4">
            <h5 class="card-header info-color white-text text-center py-4">
                <strong>Refund request</strong>
            </h5>
            <div class="card-body px-lg-5">
                <form method="post" class="text-center p-3">
                    {% csrf_token %}
                    <!-- Name -->
                    {{ form.ref_code }}
{#                    <input type="text" id="defaultSubscriptionFormPassword" class="form-control mb-4" placeholder="Name">#}
                    <!-- Message -->
                    <div class="form-group">
{#                        <textarea class="form-control rounded-3" id="exampleFormControlTextarea2" rows="5" placeholder="Message"></textarea>#}
                        {{ form.message }}
                    </div>
                    <!-- Submit button -->
                    <button class="btn btn-info btn-block" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}