backend/urls.py
from django.urls import path
from backend.views import (
    HomePageView,
    ProductDetailView,
    CrateCartView,
    RemoveCartView,
    OrderSummaryView,
    RemoveSingleCartItemView,
    CheckoutView,
    PaymentView,
    RefundView,
)

app_name = 'backend'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path("product/<int:pk>/", ProductDetailView.as_view(), name='product'),
    path("add-to-cart/<int:product_id>/", CrateCartView.as_view(), name='add_to_cart'),
    path("remove-from-cart/<int:product_id>", RemoveCartView.as_view(), name='remove-from-cart'),
    path("orders/", OrderSummaryView.as_view(), name='orders'),
    path("remove-single-cart-item/<int:product_id>", RemoveSingleCartItemView.as_view(), name='remove-single-cart-item'),
    path("checkout/", CheckoutView.as_view(), name='checkout'),
    path("payment/<payment_method>/", PaymentView.as_view(), name='payment'),
    path("request-refund/", RefundView.as_view(), name='request-refund'),
]

django_ecommerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('backend.urls', namespace='backend')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/_bottom_bar.html
<ul class="nav blue-gradient row fixed-bottom rounded">
    {% if request.user.is_authenticated %}
        <li class="nav-item dropup col text-center">
            <a class="nav-link dropdown-toggle" id="searchdropup" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-lg pr-1 mt-2 text-white" aria-hidden="false"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right bg-transparent border-0" aria-labelledby="searchdropup">
                <form class="dropdown-item form-inline justify-content-center blue darken-2 rounded-pill">
                    <div class="md-form my-0">
                        <input class="form-control mr-sm-2 white-text" type="text" placeholder="" aria-label="Search">
                    </div>
                </form>
            </div>
        </li>

        <li class="nav-item col text-center">
            <a href="" class="nav-link waves-effect white-text">
                <i class="fas fa-filter fa-lg pr-1 mt-2" aria-hidden="true"></i>
            </a>
        </li>

        <li class="nav-item col text-center">
            <a href="{% url 'backend:orders' %}" class="nav-link waves-effect white-text">
                <i class="fas fa-shopping-cart fa-lg pr-1 mt-2" aria-hidden="false" style="position: relative"></i>
                {% if cart_count %}
                    <span class="pink-text font-weight-bold badge badge-danger mt-1" style="position: absolute; top: 0.01rem; right: 0.2rem; padding: .1rem .3rem;">{{ cart_count }}</span>
                {% endif %}
            </a>
        </li>
        
        <li class="nav-item dropup col text-center">
            <a class="nav-link dropdown-toggle" id="profileDropDown" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
{#                <img src="https://mdbootstrap.com/img/Photos/Avatars/avatar-5.jpg" class="rounded-circle z-depth-0" aria-hidden="true" alt="avatar image" height="35">#}
                <i class="fas fa-user-circle fa-lg pr-1 mt-2 text-white"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right blue darken-2" aria-labelledby="profileDropDown">
                <a class="dropdown-item font-weight-bold" href="#">My account</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item font-weight-bold" href="{% url 'account_logout' %}">Log out <i class="fas fa-sign-out-alt float-right text-danger mt-1"></i></a>
            </div>
        </li>
    {% else %}

    {% endif %}
</ul>

templates/components/_cart_preview.html
<div class="col my-4">
    <!-- Heading -->
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span>Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.cart_products.count }}</span>
    </h4>

    <!-- Cart -->
    <ul class="list-group mb-3 z-depth-1">
        {% for cart in order.cart_products.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                    <h6 class="my-0">{{ cart.quantity }} x {{ cart.product.title }}</h6>
                    <small class="text-muted">{{ cart.product.description }}</small>
                </div>
                {% if cart.product.discount_price %}
                    <span class="text-muted">${{ cart.product.discount_price }}</span>
                {% else %}
                    <span class="text-muted">${{ cart.product.price }}</span>
                {% endif %}
            </li>

        {% endfor %}

        <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>${{ order.final_order_price }}</strong>
        </li>
    </ul>
    <!-- Cart -->
</div>

templates/components/_footer.html
<!-- Footer -->
<footer class="page-footer font-small blue-gradient">
      <!-- Copyright -->
      <div class="text-center py-3">
          <span class="yellow-text">
            &copy;<script>document.write(new Date().getFullYear());</script> Copyright:
          </span>
        <a href="#" class="font-weight-bold">E-Store</a>
      </div>

    {% if not request.user.is_authenticated %}
        <hr>
        <div class="container">
            <div class="row px-5">
                <a class="col btn btn-sm btn-outline-white rounded-pill" href="{% url 'account_login' %}">Login</a>
                <a class="col btn btn-sm btn-outline-white rounded-pill" href="{% url 'account_signup' %}">SignUp</a>
            </div>
        </div>
    {% endif %}
  <!-- Copyright -->
</footer>
<!-- Footer -->

templates/components/_inner_nav.html
<div class="container mb-3 mt-4">
<nav class="navbar scrolling-navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav nav-flex-icons mr-auto justify-content-center">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Outwears</a>
            </li>

          </ul>
          <!-- Links -->
        </div>
        <!-- Collapsible content -->
      </nav>
    </div>

templates/components/_menu.html
{% load static %}
    <!-- Menu -->
    <div class="menu">
        <!-- Search -->
        <div class="menu_search">
            <form action="#" id="menu_search_form" class="menu_search_form">
                <input type="text" class="search_input" placeholder="Search Item" required="required">
                <button class="menu_search_button"><img src="{% static 'images/search.png' %}" alt=""></button>
            </form>
        </div>
        <!-- Navigation -->
        <div class="menu_nav">
            <ul>
                <li><a href="#">Women</a></li>
                <li><a href="#">Men</a></li>
                <li><a href="#">Kids</a></li>
                <li><a href="#">Home Deco</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </div>
        <!-- Contact Info -->
        <div class="menu_contact">
            <div class="menu_phone d-flex flex-row align-items-center justify-content-start">
                <div><div><img src="{% static 'images/phone.svg' %}" alt="https://www.flaticon.com/authors/freepik"></div></div>
                <div>+1 912-252</div>
            </div>
            <div class="menu_social">
                <ul class="menu_social_list d-flex flex-row align-items-start justify-content-start">
                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                </ul>
            </div>
        </div>
    </div>

templates/components/_navbar.html
<!--Navbar -->
<nav class="navbar scrolling-navbar navbar-expand-lg navbar-dark pink darken-1 blue-gradient">
    <a class="navbar-brand" href="{% url 'backend:home' %}">
        <img src="https://mdbootstrap.com/img/logo/mdb-transparent.png" height="30" alt="mdb logo">
    </a>
    <button class="float-right navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-top"
            aria-controls="navbar-top" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-top">
        <ul class="navbar-nav nav-flex-icons font-weight-bold justify-content-center ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
            </li>
        </ul>
    </div>
</nav>
<!--/.Navbar -->

templates/components/_scripts.html
{% load static %}
<!-- JQuery -->
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
    $(document).ready(() => {
        // SideNav Button Initialization
        $(".button-collapse").sideNav();
        // SideNav Scrollbar Initialization
        var sideNavScrollbar = document.querySelector('.custom-scrollbar');
        var ps = new PerfectScrollbar(sideNavScrollbar);

        new WOW().init();
    });
    $('.alert').alert();
    new WOW().init();
</script>